# Generated by Django 4.0.5 on 2022-06-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crunchapp', '0004_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
